---
name: oam-experiments

path: .

windows:
  - name: code
    layout: main-horizontal
    panes:
      - type: horizontal
        commands:
          - $EDITOR

  - name: misc
    layout: even-horizontal
    panes:
      - type: horizontal
      - type: horizontal
